CREATE TABLE ers.ERS_REIMBURSEMENT (
	REIMB_ID SERIAL PRIMARY KEY,
	REIMB_AMOUNT NUMERIC NOT NULL,
	REIMB_SUBMITTED TIMESTAMP NOT NULL,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_AUTHOR NUMERIC NOT NULL,
	REIMB_RESOLVER NUMERIC,
	REIMB_STATUS_ID NUMERIC NOT NULL,
	REIMB_TYPE_ID NUMERIC NOT NULL
);

CREATE TABLE ers.ERS_USERS (
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) NOT NULL,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(150) NOT NULL,
	USER_ROLE_ID NUMERIC NOT NULL
);